class Usuario
Usuario o-- Personaje


class Personaje {
  +Morir()
  +Dañar()
  +RecibirDaño()
}
Personaje *-- Vida 
Personaje "1" o-- "1"Objeto
class Oso 
class Gato
class Perro
class Conejo
Oso --|> Personaje
Gato --|> Personaje
Perro --|> Personaje
Conejo --|> Personaje
Personaje "1" o-- "1" ZapatillasGato
Personaje "1" o-- "1" CorazonPetalos
Personaje "1" o-- "1" TrebolRuinas
Personaje "1" o-- "1" FlechaCaza
Personaje "1" o-- "1" PiedraPulir
Personaje "1" o-- "1" PlumaViento
Personaje "1" o-- "1" BolsaMonedas


class Enemigo
class Fantasma
class Iguana
class Hongo
class Boss
Fantasma --|> Enemigo
Iguana --|> Enemigo
Hongo --|> Enemigo
Boss --|> Enemigo
Enemigo *-- Vida


class Ataque 
class Lagrimas
Lagrimas --|> Ataque


class Objeto
class ZapatillasGato
class CorazonPetalos
class TrebolRuinas
class FlechaCaza
class PiedraPulir
class PlumaViento
class BolsaMonedas
ZapatillasGato --|> Objeto
CorazonPetalos --|> Objeto
TrebolRuinas --|> Objeto
FlechaCaza --|> Objeto
PiedraPulir --|> Objeto
PlumaViento --|> Objeto
BolsaMonedas --|> Objeto


Class Ataque
Ataque --|> Lagrimas
Personaje o-- Ataque


class Combate {
  +Dañar(Personaje, Enemigo)
  +RecibirDaño(Personaje, Enemigo)
}
Personaje o-- Combate
Enemigo o-- Combate


