class Usuario
Usuario --|> Personaje

class Personaje {
  +Morir()
  +Dañar()
  +RecibirDaño()
}
Personaje *-- Vida 
Personaje 

Class Enemigo
Enemigo *-- Vida

class Ataque 

class Objeto
class ZapatillasGato
class CorazonPetalos
class TrebolRuinas
class FlechaCaza
class PiedraPulir
class PlumaViento
class BolsaMonedas

ZapatillasGato --|> Objeto
CorazonPetalos --|> Objeto
TrebolRuinas --|> Objeto
FlechaCaza --|> Objeto
PiedraPulir --|> Objeto


Class Arma 


class Defensa
